#index:
#    path: /
#    controller: App\Controller\DefaultController::index

prenoms:
    path: /
    defaults: {_controller: 'App\Controller\PrenomController::index'}

resultat:
    path: /resultat
    defaults: {_controller: 'App\Controller\ResultatController::index'}