#index:
#    path: /
#    controller: App\Controller\DefaultController::index

prenoms:
    path: /
    defaults: {_controller: 'App\Controller\PrenomController::index'}



cherchenom:
    path: /bonus
    defaults: {_controller: 'App\Controller\CherchenomController::index'}

searchprenom:
    path: /prenom_search
    defaults: {_controller: 'App\Controller\CherchenomController::searchPrenom'}

searchresult:
    path: /searchresult
    defaults: {_controller: 'App\Controller\CherchenomController::howManyPerYear'}

searchyear:
    path: /searchyear
    defaults: {_controller: 'App\Controller\CherchenomController::searchYear'}